Fixed android resource linking failure
Ref: https://github.com/yamill/react-native-orientation/issues/369

The android build failed with the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-orientation:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
```

Therefore, upgraded compileSdkVersion fix it.